---
- id: strip-exif
  name: strip-exif
  description: strip exif metadata except for orientation
  language: docker
  types: ["image"]
  entry: exiftool
  exclude_types: ["svg"]
  args:
    [
      "-all=",
      "--icc_profile:all",
      "-tagsfromfile",
      "@",
      "-orientation",
      "-overwrite_original",
    ]
